---
#
#/ ____|  __ \ / ____|  __ \
#| |    | |__) | (___ | |__) |__  _ __  _   _ _ __
#| |    |  ___/ \___ \|  ___/ _ \| '_ \| | | | '_ \
#| |____| |     ____) | |  | (_) | |_) | |_| | |_) |
#\_____|_|    |_____/|_|   \___/| .__/ \__,_| .__/
#                   | |                    | |
#                   |_|                    |_|

# CPSPopupTask
# Warning this will show delay clicks
CPSTask: false

# Warning Warning #Warning
# If CPSTask is true put CPSListener to false elseif CPSListener is true make sure to put CPSTask to false.

# CPSListener
# Warning This will show the player CPS No delay
CPSListener: true

# use & for color
# use {cps} to show cps
CPSPopup: "&6CPS: &3{cps}"
...
